declare @filecount as tinyint
declare @sqlbulk as varchar (4000)

--This variable is used to loop through all of the files and is also used for the table numbers
set @filecount =1

While(@filecount < 37)
	begin
		SET @sqlbulk = 'CREATE TABLE [dbo].[ABPlusData_' + convert(varchar, @filecount) + '](
		[UPRN] [bigint] NOT NULL,
		[UDPRN] [int]  NULL,
		[CHANGE_TYPE] [char](1) NOT NULL,
		[STATE] [tinyint]  NULL,
		[STATE_DATE] [datetime] NULL,
		[CLASS] [char](6) NOT NULL,
		[PARENT_UPRN] [bigint]  NULL,
		[X_COORDINATE] [float]  NOT NULL,
		[Y_COORDINATE] [float] NOT NULL,
		[LATITUDE] [float] NOT NULL,
		[LONGITUDE] [float] NOT NULL,
		[RPC] [tinyint]  NOT NULL,
		[LOCAL_CUSTODIAN_CODE] [smallint]  NOT NULL,
		[COUNTRY] [char](1) NOT NULL,
		[LA_START_DATE] [datetime] NOT NULL,
		[LAST_UPDATE_DATE] [datetime] NOT NULL,
		[ENTRY_DATE] [datetime] NOT NULL,
		[RM_ORGANISATION_NAME] [varchar](60) NOT NULL,
		[LA_ORGANISATION] [varchar](100) NULL,
		[DEPARTMENT_NAME] [varchar](60) NULL,
		[LEGAL_NAME] [varchar](60) NULL,
		[SUB_BUILDING_NAME] [varchar](30) NULL,
		[BUILDING_NAME] [varchar](50) NULL,
		[BUILDING_NUMBER] [smallint] NULL,
		[SAO_START_NUMBER] [smallint]  NULL,
		[SAO_START_SUFFIX] [char](2) NULL,
		[SAO_END_NUMBER] [smallint] NULL,
		[SAO_END_SUFFIX] [varchar](2) NULL,
		[SAO_TEXT] [varchar](90) NULL,
		[ALT_LANGUAGE_SAO_TEXT] [varchar](90) NULL,
		[PAO_START_NUMBER] [smallint] NULL,
		[PAO_START_SUFFIX] [char](2) NULL,
		[PAO_END_NUMBER] [smallint] NULL,
		[PAO_END_SUFFIX] [char](2)  NULL,
		[PAO_TEXT] [varchar](90)  NULL,
		[ALT_LANGUAGE_PAO_TEXT] [varchar](90)  NULL,
		[USRN] [int] NOT NULL,
		[USRN_MATCH_INDICATOR] [tinyint] NOT NULL,
		[AREA_NAME] [varchar](40) NULL,
		[LEVEL] [varchar](30) NULL,
		[OFFICIAL_FLAG] [char](1) NULL,
		[OS_ADDRESS_TOID] [varchar](20) NULL,
		[OS_ADDRESS_TOID_VERSION] [smallint] NULL,
		[OS_ROADLINK_TOID] [varchar](20) NULL,
		[OS_ROADLINK_TOID_VERSION] [smallint] NULL,
		[OS_TOPO_TOID] [varchar](20) NULL,
		[OS_TOPO_TOID_VERSION] [smallint] NULL,
		[VOA_CT_RECORD] [bigint] NULL,
		[VOA_NDR_RECORD] [bigint] NULL,
		[STREET_DESCRIPTION] [varchar](100) NOT NULL,
		[ALT_LANGUAGE_STREET_DESCRIPTION] [varchar](100) NULL,
		[DEPENDENT_THOROUGHFARE] [varchar](80) NULL,
		[THOROUGHFARE] [varchar](80) NULL,
		[WELSH_DEPENDENT_THOROUGHFARE] [varchar](80) NULL,
		[WELSH_THOROUGHFARE] [varchar](80) NULL,
		[DOUBLE_DEPENDENT_LOCALITY] [varchar](35) NULL,
		[DEPENDENT_LOCALITY] [varchar](35) NULL,
		[LOCALITY] [varchar](35) NULL,
		[WELSH_DEPENDENT_LOCALITY] [varchar](35) NULL,
		[WELSH_DOUBLE_DEPENDENT_LOCALITY] [varchar](35) NULL,
		[TOWN_NAME] [varchar](30) NULL,
		[ADMINISTRATIVE_AREA] [varchar](30) NOT NULL,
		[POST_TOWN] [varchar](35) NULL,
		[WELSH_POST_TOWN] [varchar](30) NULL,
		[POSTCODE] [char](8) NULL,
		[POSTCODE_LOCATOR] [char](8) NOT NULL,
		[POSTCODE_TYPE] [char](1) NULL,
		[DELIVERY_POINT_SUFFIX] [char](2) NULL,
		[ADDRESSBASE_POSTAL] [char](1) NOT NULL,
		[PO_BOX_NUMBER] [varchar](6) NULL,
		[WARD_CODE] [varchar](9) NULL,
		[PARISH_CODE] [varchar](9) NULL,
		[RM_START_DATE] [datetime] NULL,
		[MULTI_OCC_COUNT] [smallint] NULL,
		[VOA_NDR_P_DESC_CODE] [char](5) NULL,
		[VOA_NDR_SCAT_CODE] [char](4) NULL,
		[ALT_LANGUAGE] [char](3)  NULL
	) ON [PRIMARY]'

		--print @sqlbulk
		print 'Creating tabel ' + convert(varchar, @filecount)
		--print (@sqlbulk)
		exec (@sqlbulk)

	  Set @filecount = @filecount+1
	end  



--Create the master table that the data will be moved to once loaded
print 'Create master table'
CREATE TABLE [dbo].[ABPlusData](
	[UPRN] [bigint] NOT NULL,
	[UDPRN] [int]  NULL,
	[CHANGE_TYPE] [char](1) NOT NULL,
	[STATE] [tinyint]  NULL,
	[STATE_DATE] [datetime] NULL,
	[CLASS] [char](6) NOT NULL,
	[PARENT_UPRN] [bigint]  NULL,
	[X_COORDINATE] [float]  NOT NULL,
	[Y_COORDINATE] [float] NOT NULL,
	[LATITUDE] [float] NOT NULL,
	[LONGITUDE] [float] NOT NULL,
	[RPC] [tinyint]  NOT NULL,
	[LOCAL_CUSTODIAN_CODE] [smallint]  NOT NULL,
	[COUNTRY] [char](1) NOT NULL,
	[LA_START_DATE] [datetime] NOT NULL,
	[LAST_UPDATE_DATE] [datetime] NOT NULL,
	[ENTRY_DATE] [datetime] NOT NULL,
	[RM_ORGANISATION_NAME] [varchar](60) NOT NULL,
	[LA_ORGANISATION] [varchar](100) NULL,
	[DEPARTMENT_NAME] [varchar](60) NULL,
	[LEGAL_NAME] [varchar](60) NULL,
	[SUB_BUILDING_NAME] [varchar](30) NULL,
	[BUILDING_NAME] [varchar](50) NULL,
	[BUILDING_NUMBER] [smallint] NULL,
	[SAO_START_NUMBER] [smallint]  NULL,
	[SAO_START_SUFFIX] [char](2) NULL,
	[SAO_END_NUMBER] [smallint] NULL,
	[SAO_END_SUFFIX] [varchar](2) NULL,
	[SAO_TEXT] [varchar](90) NULL,
	[ALT_LANGUAGE_SAO_TEXT] [varchar](90) NULL,
	[PAO_START_NUMBER] [smallint] NULL,
	[PAO_START_SUFFIX] [char](2) NULL,
	[PAO_END_NUMBER] [smallint] NULL,
	[PAO_END_SUFFIX] [char](2)  NULL,
	[PAO_TEXT] [varchar](90)  NULL,
	[ALT_LANGUAGE_PAO_TEXT] [varchar](90)  NULL,
	[USRN] [int] NOT NULL,
	[USRN_MATCH_INDICATOR] [tinyint] NOT NULL,
	[AREA_NAME] [varchar](40) NULL,
	[LEVEL] [varchar](30) NULL,
	[OFFICIAL_FLAG] [char](1) NULL,
	[OS_ADDRESS_TOID] [varchar](20) NULL,
	[OS_ADDRESS_TOID_VERSION] [smallint] NULL,
	[OS_ROADLINK_TOID] [varchar](20) NULL,
	[OS_ROADLINK_TOID_VERSION] [smallint] NULL,
	[OS_TOPO_TOID] [varchar](20) NULL,
	[OS_TOPO_TOID_VERSION] [smallint] NULL,
	[VOA_CT_RECORD] [bigint] NULL,
	[VOA_NDR_RECORD] [bigint] NULL,
	[STREET_DESCRIPTION] [varchar](100) NOT NULL,
	[ALT_LANGUAGE_STREET_DESCRIPTION] [varchar](100) NULL,
	[DEPENDENT_THOROUGHFARE] [varchar](80) NULL,
	[THOROUGHFARE] [varchar](80) NULL,
	[WELSH_DEPENDENT_THOROUGHFARE] [varchar](80) NULL,
	[WELSH_THOROUGHFARE] [varchar](80) NULL,
	[DOUBLE_DEPENDENT_LOCALITY] [varchar](35) NULL,
	[DEPENDENT_LOCALITY] [varchar](35) NULL,
	[LOCALITY] [varchar](35) NULL,
	[WELSH_DEPENDENT_LOCALITY] [varchar](35) NULL,
	[WELSH_DOUBLE_DEPENDENT_LOCALITY] [varchar](35) NULL,
	[TOWN_NAME] [varchar](30) NULL,
	[ADMINISTRATIVE_AREA] [varchar](30) NOT NULL,
	[POST_TOWN] [varchar](35) NULL,
	[WELSH_POST_TOWN] [varchar](30) NULL,
	[POSTCODE] [char](8) NULL,
	[POSTCODE_LOCATOR] [char](8) NOT NULL,
	[POSTCODE_TYPE] [char](1) NULL,
	[DELIVERY_POINT_SUFFIX] [char](2) NULL,
	[ADDRESSBASE_POSTAL] [char](1) NOT NULL,
	[PO_BOX_NUMBER] [varchar](6) NULL,
	[WARD_CODE] [varchar](9) NULL,
	[PARISH_CODE] [varchar](9) NULL,
	[RM_START_DATE] [datetime] NULL,
	[MULTI_OCC_COUNT] [smallint] NULL,
	[VOA_NDR_P_DESC_CODE] [char](5) NULL,
	[VOA_NDR_SCAT_CODE] [char](4) NULL,
	[ALT_LANGUAGE] [char](3)  NULL
) ON [PRIMARY]
GO
